name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up with JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 21

      - name: Clean and build
        run: ./gradlew clean build --info --stacktrace